apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: configuration-service
  annotations:
    tags: core-services, configuration-service
    template.openshift.io/provider-display-name: platform team
    description: Configuration Service
labels:
  application: configuration-service
parameters:
  - name: INFRA_NAMESPACE
    description: Name of the infrastructure project.
    displayName: Infra Namespace
    value: core-services-infra
    required: true
  - name: NAMESPACE
    description: Namespace of the environment.
    displayName: Namespace
    value: core-services-dev
    required: true
  - name: NAME_SUFFIX
    description: Suffix applied to the names of the objects created.
    displayName: Name Suffix
    value: ""
  - name: BUILD_TAG
    description: Name of the ImageStreamTag to build.
    displayName: Build Tag
    value: latest
  - name: DEPLOY_TAG
    description: Name of the ImageStreamTag to deploy.
    displayName: Deploy Tag
    value: latest
  - name: ROUTE_HOST
    description: Host for the route.
    displayName: Route Host
    value: ""
  - description: Username for MongoDB user that will be used for accessing the database.
    displayName: MongoDB Connection Username
    from: user[A-Z0-9]{3}
    generate: expression
    name: MONGODB_USER
    required: true
  - description: Password for the MongoDB connection user.
    displayName: MongoDB Connection Password
    from: "[a-zA-Z0-9]{16}"
    generate: expression
    name: MONGODB_PASSWORD
    required: true
  - description: Password for the database admin user.
    displayName: MongoDB Admin Password
    from: "[a-zA-Z0-9]{16}"
    generate: expression
    name: MONGODB_ADMIN_PASSWORD
    required: true
objects:
  # MongoDB Objects
  # NOTE: Secret will generate new values if updated, so this is only for branch deployments.
  - apiVersion: v1
    kind: Secret
    metadata:
      annotations:
        template.openshift.io/expose-admin_password: "{.data['database-admin-password']}"
        template.openshift.io/expose-database_name: "{.data['database-name']}"
        template.openshift.io/expose-password: "{.data['database-password']}"
        template.openshift.io/expose-username: "{.data['database-user']}"
      labels:
        app: configuration-service${NAME_SUFFIX}
        component: database
        apply-init: "true"
        apply-branch: "true"
      name: configuration-service-mongodb${NAME_SUFFIX}
    stringData:
      database-admin-password: ${MONGODB_ADMIN_PASSWORD}
      database-name: configurationDb
      database-password: ${MONGODB_PASSWORD}
      database-user: ${MONGODB_USER}
      database-uri: mongodb://configuration-service-mongodb${NAME_SUFFIX}:27017
      database-tls: 'false'
  # PersistentVolumeClaim is only generated for branch deployment to avoid losing persistent data.
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      labels:
        app: configuration-service${NAME_SUFFIX}
        component: database
        apply-init: "true"
        apply-branch: "true"
      name: configuration-service-mongodb${NAME_SUFFIX}
    spec:
      storageClassName: azure-disk
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        template.openshift.io/expose-uri: mongodb://{.spec.clusterIP}:{.spec.ports[?(.name=="mongo")].port}
      labels:
        app: configuration-service${NAME_SUFFIX}
        component: database
        apply-branch: "true"
        apply-dev: "true"
        apply-test: "true"
        apply-staging: "true"
        apply-prod: "true"
      name: configuration-service-mongodb${NAME_SUFFIX}
    spec:
      ports:
        - name: mongo
          nodePort: 0
          port: 27017
          protocol: TCP
          targetPort: 27017
      selector:
        app: configuration-service${NAME_SUFFIX}
        component: database
      sessionAffinity: None
      type: ClusterIP
    status:
      loadBalancer: {}
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      annotations:
        template.alpha.openshift.io/wait-for-ready: "true"
      labels:
        app: configuration-service${NAME_SUFFIX}
        component: database
        apply-branch: "true"
        apply-dev: "true"
        apply-test: "true"
        apply-staging: "true"
        apply-prod: "true"
      name: configuration-service-mongodb${NAME_SUFFIX}
    spec:
      replicas: 1
      selector:
        app: configuration-service${NAME_SUFFIX}
        component: database
      strategy:
        type: Recreate
      template:
        metadata:
          labels:
            app: configuration-service${NAME_SUFFIX}
            component: database
        spec:
          containers:
            - capabilities: {}
              env:
                - name: MONGODB_USER
                  valueFrom:
                    secretKeyRef:
                      key: database-user
                      name: configuration-service-mongodb${NAME_SUFFIX}
                - name: MONGODB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: database-password
                      name: configuration-service-mongodb${NAME_SUFFIX}
                - name: MONGODB_ADMIN_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: database-admin-password
                      name: configuration-service-mongodb${NAME_SUFFIX}
                - name: MONGODB_DATABASE
                  valueFrom:
                    secretKeyRef:
                      key: database-name
                      name: configuration-service-mongodb${NAME_SUFFIX}
              image: " "
              imagePullPolicy: IfNotPresent
              livenessProbe:
                initialDelaySeconds: 30
                tcpSocket:
                  port: 27017
                timeoutSeconds: 1
              name: mongodb
              ports:
                - containerPort: 27017
                  protocol: TCP
              readinessProbe:
                exec:
                  command:
                    - /bin/sh
                    - -i
                    - -c
                    - mongo 127.0.0.1:27017/$MONGODB_DATABASE -u $MONGODB_USER -p $MONGODB_PASSWORD
                      --eval="quit()"
                initialDelaySeconds: 3
                timeoutSeconds: 1
              resources:
                limits:
                  cpu: 200m
                  memory: 500Mi
                requests:
                  cpu: 20m
                  memory: 200Mi
              securityContext:
                capabilities: {}
                privileged: false
              terminationMessagePath: /dev/termination-log
              volumeMounts:
                - mountPath: /var/lib/mongodb/data
                  name: configuration-service-data
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          volumes:
            - name: configuration-service-data
              persistentVolumeClaim:
                claimName: configuration-service-mongodb${NAME_SUFFIX}
      triggers:
        - imageChangeParams:
            automatic: true
            containerNames:
              - mongodb
            from:
              kind: ImageStreamTag
              name: mongodb:latest
              namespace: openshift
          type: ImageChange

  # Configuration Service Objects

  # ImageStream is here for reference.
  # There is a single ImageStream created in the infra project.
  - apiVersion: v1
    kind: ImageStream
    metadata:
      labels:
        app: configuration-service
        component: api
        apply-infra: "true"
      name: configuration-service
      namespace: ${INFRA_NAMESPACE}
    spec:
      tags:
        - name: ${BUILD_TAG}
          from:
            kind: DockerImage
            name: ghcr.io/govalta/configuration-service:${BUILD_TAG}
          referencePolicy:
            type: Local

  # DeploymentConfig (and Service and Route) is created in each environment of the
  # primary pipeline as well as branch deployment.
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      labels:
        app: configuration-service${NAME_SUFFIX}
        component: api
        apply-branch: "true"
        apply-dev: "true"
        apply-test: "true"
        apply-staging: "true"
        apply-prod: "true"
      name: configuration-service${NAME_SUFFIX}
    spec:
      replicas: 3
      revisionHistoryLimit: 3
      selector:
        app: configuration-service${NAME_SUFFIX}
        component: api
      strategy:
        type: Rolling
        rollingParams:
          timeoutSeconds: 600
          maxUnavailable: 25%
          maxSurge: 25%
        activeDeadlineSeconds: 21600
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 20m
            memory: 50Mi
      template:
        metadata:
          labels:
            app: configuration-service${NAME_SUFFIX}
            component: api
        spec:
          containers:
            - envFrom:
                - configMapRef:
                    name: configuration-service
                - secretRef:
                    name: configuration-service
              env:
                - name: PORT
                  value: "3333"
                - name: MONGO_USER
                  valueFrom:
                    secretKeyRef:
                      key: database-user
                      name: configuration-service-mongodb${NAME_SUFFIX}
                - name: MONGO_URI
                  valueFrom:
                    secretKeyRef:
                      key: database-uri
                      name: configuration-service-mongodb${NAME_SUFFIX}
                - name: MONGO_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: database-password
                      name: configuration-service-mongodb${NAME_SUFFIX}
                - name: MONGO_DB
                  valueFrom:
                    secretKeyRef:
                      key: database-name
                      name: configuration-service-mongodb${NAME_SUFFIX}
                - name: MONGO_TLS
                  valueFrom:
                    secretKeyRef:
                      key: database-tls
                      name: configuration-service-mongodb${NAME_SUFFIX}
              imagePullPolicy: IfNotPresent
              name: configuration-service
              ports:
                - containerPort: 3333
                  name: http
                  protocol: TCP
              resources:
                limits:
                  cpu: 200m
                  memory: 200Mi
                requests:
                  cpu: 20m
                  memory: 50Mi
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              readinessProbe:
                httpGet:
                  path: /
                  port: 3333
                  scheme: HTTP
                initialDelaySeconds: 10
                timeoutSeconds: 1
                periodSeconds: 30
                successThreshold: 1
                failureThreshold: 3
              livenessProbe:
                httpGet:
                  path: /
                  port: 3333
                  scheme: HTTP
                initialDelaySeconds: 60
                timeoutSeconds: 1
                periodSeconds: 60
                successThreshold: 1
                failureThreshold: 3
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
      test: false
      triggers:
        - imageChangeParams:
            containerNames:
              - configuration-service
            from:
              kind: ImageStreamTag
              name: configuration-service:${DEPLOY_TAG}
              namespace: ${INFRA_NAMESPACE}
          type: ImageChange
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: configuration-service${NAME_SUFFIX}
        component: api
        apply-branch: "true"
        apply-dev: "true"
        apply-test: "true"
        apply-staging: "true"
        apply-prod: "true"
      name: configuration-service${NAME_SUFFIX}
    spec:
      ports:
        - name: http
          port: 3333
          protocol: TCP
          targetPort: 3333
      selector:
        app: configuration-service${NAME_SUFFIX}
        component: api
      sessionAffinity: None
      type: ClusterIP
  - apiVersion: v1
    kind: Route
    metadata:
      labels:
        app: configuration-service${NAME_SUFFIX}
        component: api
        apply-branch: "true"
        apply-dev: "true"
        apply-test: "true"
        apply-staging: "true"
        apply-prod: "true"
      name: configuration-service${NAME_SUFFIX}
    spec:
      host: ${ROUTE_HOST}
      port:
        targetPort: http
      tls:
        termination: edge
      to:
        kind: Service
        name: configuration-service${NAME_SUFFIX}
        weight: 100
      wildcardPolicy: None
